{{- if not .Values.istio.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "package-registry.fullversionname" . }}
  labels:
    {{- include "package-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "package-registry.selectorLabels" . | nindent 4 }}
{{- end }}